# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\tprocessor\"\x1b\n\x05Point\x12\x12\n\npixelPoint\x18\x01 \x03(\x05\"\x1f\n\x0c\x41veragePixel\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x05\x32P\n\x0eImageProcessor\x12>\n\x0fGetAveragePixel\x12\x10.processor.Point\x1a\x17.processor.AveragePixel\"\x00\x62\x06proto3')



_POINT = DESCRIPTOR.message_types_by_name['Point']
_AVERAGEPIXEL = DESCRIPTOR.message_types_by_name['AveragePixel']
Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:processor.Point)
  })
_sym_db.RegisterMessage(Point)

AveragePixel = _reflection.GeneratedProtocolMessageType('AveragePixel', (_message.Message,), {
  'DESCRIPTOR' : _AVERAGEPIXEL,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:processor.AveragePixel)
  })
_sym_db.RegisterMessage(AveragePixel)

_IMAGEPROCESSOR = DESCRIPTOR.services_by_name['ImageProcessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT._serialized_start=26
  _POINT._serialized_end=53
  _AVERAGEPIXEL._serialized_start=55
  _AVERAGEPIXEL._serialized_end=86
  _IMAGEPROCESSOR._serialized_start=88
  _IMAGEPROCESSOR._serialized_end=168
# @@protoc_insertion_point(module_scope)
